services:
  keycloak-db:
    container_name: keycloak-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-keycloak-db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-keycloak-db}
      POSTGRES_DB: keycloak_db
      PGDATA: /data/postgres
    volumes:
      - dbdata-keycloak:/data/postgres
  keycloak:
    image: keycloak/keycloak:26.0
    container_name: keycloak
    restart: always
    ports:
      - 9001:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak_db
      DB_USER: ${POSTGRES_USER:-keycloak-db}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-keycloak-db}
      KC_HOSTNAME: ${KC_HOSTNAME:-localhost}
      KEYCLOAK_USER: ${KEYCLOAK_USER:-user}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-user_password}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin_password}
      KC_HTTP_ENABLED: true
      HTTP_ADDRESS_FORWARDING: true
    command: start
    volumes:
      - ./keycloak-realms:/opt/keycloak/data/import
    depends_on:
      - keycloak-db
    links:
      - "keycloak-db:keycloak-db"
  mongo-tasks:
    container_name: mongo-tasks
    image: mongo:8.0
    restart: always
    ports:
      - 9002:27017
    volumes:
      - dbdata-tasks:/data/db
networks:
  tasks:
    driver: bridge
volumes:
  dbdata-keycloak:
  dbdata-tasks: